import type { RagDocument } from "@/lib/ipc";

/**
 * Split a document list into ordinary attachable documents and documents
 * Ally generated for THIS context — used by the Setup wizard's Documents
 * step so a generated document renders as an auto-included, view-only
 * "Generated by Ally" entry instead of an attachable checkbox (spec
 * 2026-08-27). A document is `generated` when `source === "generated"`
 * AND its `context_ids` includes `contextId`; a non-generated document is
 * always `attachable`, regardless of its `context_ids`; a generated
 * document belonging to a different context (or to none) is excluded
 * from BOTH lists — it isn't relevant to the context being edited, so it
 * isn't offered as attachable either. `contextId` undefined (creation
 * mode, nothing can have been generated yet) excludes every generated
 * document.
 */
export function splitDocuments(
  docs: readonly RagDocument[],
  contextId: string | undefined,
): { attachable: RagDocument[]; generated: RagDocument[] } {
  const attachable: RagDocument[] = [];
  const generated: RagDocument[] = [];
  for (const d of docs) {
    if (d.source !== "generated") {
      attachable.push(d);
    } else if (contextId && d.context_ids.includes(contextId)) {
      generated.push(d);
    }
    // else: a generated doc for a different/no context — excluded from both.
  }
  return { attachable, generated };
}
