import { cleanup, fireEvent, render, screen, waitFor, within } from "@testing-library/react";
import { afterEach, describe, expect, it, vi } from "vitest";

import { ContextSetup } from "@/components/context/ContextSetup";
import { BackendProvider } from "@/lib/backend";
import type { ConvaBackend } from "@/lib/backend/ConvaBackend";
import type { ConversationContext } from "@/lib/ipc";

afterEach(cleanup);

// Minimal fake — the wizard only calls rag.list() on mount; the rest is local
// React state until Finish (which these tests don't reach). capabilities()
// is stubbed because ContextSetup now calls useCapabilities() unconditionally
// (Generated by Ally's View button gating) — resolving null is fine for
// tests that don't care about partnerWindow.
function fakeBackend(): ConvaBackend {
  return {
    rag: { list: vi.fn().mockResolvedValue([]) },
    capabilities: vi.fn().mockResolvedValue(null),
  } as unknown as ConvaBackend;
}

function renderSetup(overrides?: Partial<ConvaBackend>) {
  render(
    <BackendProvider backend={{ ...fakeBackend(), ...overrides } as ConvaBackend}>
      <ContextSetup onDone={() => undefined} onCancel={() => undefined} />
    </BackendProvider>,
  );
}

function pastedDoc(id: string, fileName: string) {
  return { ...ragDoc(id, fileName), source: "pasted" as const };
}

function ragDoc(id: string, fileName: string) {
  return {
    id,
    file_name: fileName,
    enabled: true,
    chunk_count: 1,
    ingested_at_unix_ms: 0,
    source: "file" as const,
    context_ids: [],
    size_bytes: 10,
  };
}

/** Walk the wizard to step 2 (the document slots). */
async function gotoStepTwo() {
  const name = await screen.findByPlaceholderText(/Senior Accountant interview/i);
  fireEvent.change(name, { target: { value: "New one" } });
  fireEvent.click(screen.getByRole("button", { name: "Next" }));
}

/** The minimum of a DataTransfer these handlers read. */
function transfer({ files = [], docId = "" }: { files?: File[]; docId?: string }) {
  return { files, getData: () => docId, dropEffect: "", types: [] };
}

describe("ContextSetup wizard", () => {
  it("offers all five conversation types", async () => {
    renderSetup();
    // findBy flushes the mount effect (rag.list) so no act() warnings.
    expect(await screen.findByRole("button", { name: "Interview" })).toBeInTheDocument();
    expect(screen.getByText("Start with a template")).toBeInTheDocument();
    expect(screen.getByText(/Choose the conversation pattern Ally should prepare for/i)).toBeInTheDocument();
    for (const type of ["Company meeting", "Sales call", "Live stream", "Other"]) {
      expect(screen.getByRole("button", { name: type })).toBeInTheDocument();
    }
  });

  it("swaps the Name/Goal/Key terms starter skeleton when the category changes", async () => {
    renderSetup();
    expect(await screen.findByPlaceholderText(/Senior Accountant interview/i)).toBeInTheDocument();
    expect(screen.getByPlaceholderText(/Prep for technical GAAP/i)).toBeInTheDocument();

    fireEvent.click(screen.getByRole("button", { name: "Sales call" }));

    expect(screen.getByPlaceholderText(/Discovery call with Acme Corp/i)).toBeInTheDocument();
    expect(screen.getByPlaceholderText(/Understand their pain points/i)).toBeInTheDocument();
    expect(screen.queryByPlaceholderText(/Senior Accountant interview/i)).toBeNull();
    // A category switch is example copy only — it must never touch what the
    // user already typed.
    fireEvent.change(screen.getByPlaceholderText(/Discovery call with Acme Corp/i), {
      target: { value: "My real title" },
    });
    fireEvent.click(screen.getByRole("button", { name: "Live stream" }));
    expect(screen.getByDisplayValue("My real title")).toBeInTheDocument();
  });

  it("adapts participation lenses by Context and saves the approved claim policy", async () => {
    const save = vi.fn().mockResolvedValue({ id: "s1" });
    const prepare = vi.fn().mockResolvedValue({ id: "s1" });
    const backend = {
      rag: { list: vi.fn().mockResolvedValue([]) },
      context: { save, prepare },
      capabilities: vi.fn().mockResolvedValue(null),
    } as unknown as ConvaBackend;

    render(
      <BackendProvider backend={backend}>
        <ContextSetup onDone={() => undefined} onCancel={() => undefined} />
      </BackendProvider>,
    );

    fireEvent.change(await screen.findByPlaceholderText(/Senior Accountant interview/i), {
      target: { value: "Live verification" },
    });
    fireEvent.click(screen.getByRole("button", { name: "Live stream" }));
    const role = screen.getByRole("combobox", { name: /Your role in this conversation/i });
    expect(role).toHaveValue("live_host");
    fireEvent.change(role, { target: { value: "live_producer" } });
    expect(screen.getByText(/Manage the verification queue/i)).toBeInTheDocument();

    fireEvent.click(screen.getByRole("button", { name: "Next" }));
    expect(
      screen.getByRole("checkbox", { name: /Automatically check valuable claims/i }),
    ).toBeChecked();
    expect(
      screen.getByRole("checkbox", { name: /General web discovery/i }),
    ).toBeChecked();
    expect(screen.getByText(/Web research sends only the normalized claim/i)).toBeInTheDocument();

    fireEvent.click(screen.getByRole("button", { name: "Next" }));
    expect(screen.getByText("Producer / researcher")).toBeInTheDocument();
    fireEvent.click(screen.getByRole("button", { name: "Finish" }));

    await waitFor(() => expect(save).toHaveBeenCalled());
    expect(save.mock.calls[0]![0]).toMatchObject({
      category: "live_stream",
      participation_lens: "live_producer",
      source_policy: {
        allowed_classes: [
          "primary_official",
          "recognized_reporting",
          "specialist_reference",
          "general_web_discovery",
        ],
        allow_open_web: true,
        allow_automatic_checks: true,
        freshness_window_hours: 24,
      },
    });
  });

  it("shows the job-description field only for Interview", async () => {
    renderSetup();
    // Interview is the default type → JD field present.
    expect(await screen.findByPlaceholderText(/job description/i)).toBeInTheDocument();
    // Switching to an internal type hides it.
    fireEvent.click(screen.getByRole("button", { name: "Company meeting" }));
    expect(screen.queryByPlaceholderText(/job description/i)).toBeNull();
  });

  it("defaults web research on for the Interview type", async () => {
    renderSetup();
    // Name is required to advance to step 2.
    const name = await screen.findByPlaceholderText(/Senior Accountant interview/i);
    fireEvent.change(name, { target: { value: "My interview" } });
    fireEvent.click(screen.getByRole("button", { name: "Next" }));
    // The research toggle (now joined on step 2 by the interview-only deep
    // Q&A checkbox) is on by default for Interview.
    expect(
      screen.getByRole("checkbox", { name: /research the web for context/i }),
    ).toBeChecked();
  });

  it("preserves generated-document ids and derived fields across an edit-save", async () => {
    const save = vi.fn().mockResolvedValue({ id: "s1" });
    const prepare = vi.fn().mockResolvedValue({ id: "s1" });
    const backend = {
      rag: { list: vi.fn().mockResolvedValue([]) },
      context: { save, prepare },
      capabilities: vi.fn().mockResolvedValue(null),
    } as unknown as ConvaBackend;

    const initial: ConversationContext = {
      id: "s1",
      title: "Amazon Interview",
      purpose: "",
      job_description: null,
      category: "interview",
      status: "ready",
      created_at_unix_ms: 0,
      updated_at_unix_ms: 0,
      source_doc_ids: [],
      auto_generate_context: true,
      research_enabled: true,
      deep_qa_enabled: true,
      key_terms: [],
      glossary: [],
      glossary_definitions: { "API Gateway": "managed API front door." },
      knowledge_profile_id: "kp-1",
      personas: [],
      chosen_persona_id: null,
      conversation_id: null,
      dossier_doc_id: "doc-1",
      research_doc_id: "doc-2",
      qa_doc_id: "doc-3",
      resources_stale: true,
    };

    render(
      <BackendProvider backend={backend}>
        <ContextSetup initial={initial} onDone={() => undefined} onCancel={() => undefined} />
      </BackendProvider>,
    );

    await screen.findByDisplayValue("Amazon Interview");
    fireEvent.click(screen.getByRole("button", { name: "Next" }));
    fireEvent.click(screen.getByRole("button", { name: "Next" }));
    fireEvent.click(screen.getByRole("button", { name: "Finish" }));

    await waitFor(() => expect(save).toHaveBeenCalled());
    const payload = save.mock.calls[0][0];
    expect(payload.research_doc_id).toBe("doc-2");
    expect(payload.qa_doc_id).toBe("doc-3");
    expect(payload.glossary_definitions).toEqual({ "API Gateway": "managed API front door." });
    expect(payload.resources_stale).toBe(true);
  });

  it("saves pending edits (e.g. a just-checked deep-QA box) before regenerating, and keeps later saves in sync with the fresh doc ids", async () => {
    const save = vi.fn().mockResolvedValue({ id: "s1" });
    const generateDossier = vi.fn().mockResolvedValue({
      id: "s1",
      dossier_doc_id: "doc-1-new",
      research_doc_id: "doc-2-new",
      qa_doc_id: "doc-3-new",
      glossary: ["SOC 2"],
      glossary_definitions: { "SOC 2": "a compliance framework." },
      resources_stale: false,
    });
    const prepare = vi.fn().mockResolvedValue({ id: "s1" });
    const backend = {
      rag: { list: vi.fn().mockResolvedValue([]) },
      context: { save, generateDossier, prepare },
      capabilities: vi.fn().mockResolvedValue(null),
    } as unknown as ConvaBackend;

    const initial: ConversationContext = {
      id: "s1",
      title: "Amazon Interview",
      purpose: "",
      job_description: null,
      category: "interview",
      status: "ready",
      created_at_unix_ms: 0,
      updated_at_unix_ms: 0,
      source_doc_ids: [],
      auto_generate_context: true,
      research_enabled: true,
      deep_qa_enabled: false,
      key_terms: [],
      glossary: [],
      glossary_definitions: {},
      knowledge_profile_id: "kp-1",
      personas: [],
      chosen_persona_id: null,
      conversation_id: null,
      dossier_doc_id: "doc-1",
      research_doc_id: "doc-2",
      qa_doc_id: "doc-3",
      resources_stale: false,
    };

    render(
      <BackendProvider backend={backend}>
        <ContextSetup initial={initial} onDone={() => undefined} onCancel={() => undefined} />
      </BackendProvider>,
    );

    await screen.findByDisplayValue("Amazon Interview");
    fireEvent.click(screen.getByRole("button", { name: "Next" }));

    // Check the deep-QA box — local wizard state only, not yet persisted.
    fireEvent.click(
      screen.getByRole("checkbox", { name: /research common interview questions/i }),
    );
    fireEvent.click(screen.getByRole("button", { name: "Regenerate resources" }));

    // The save that regenerate fires must carry the just-checked box — the
    // concrete bug this closes: generateDossier reads the saved session
    // from disk, so without this save it silently ran against the old
    // (unchecked) value and produced no Q&A doc.
    await waitFor(() => expect(save).toHaveBeenCalled());
    expect(save.mock.calls[0]![0].deep_qa_enabled).toBe(true);
    expect(generateDossier).toHaveBeenCalledWith("s1");

    // A later save (e.g. Finish, without another edit) must use the FRESH
    // doc ids generateDossier just returned, not the stale `initial` ones —
    // otherwise it would silently revert the just-regenerated docs.
    await waitFor(() => expect(generateDossier).toHaveReturned());
    fireEvent.click(screen.getByRole("button", { name: "Next" }));
    fireEvent.click(screen.getByRole("button", { name: "Finish" }));
    await waitFor(() => expect(save).toHaveBeenCalledTimes(2));
    const secondPayload = save.mock.calls[1]![0];
    expect(secondPayload.dossier_doc_id).toBe("doc-1-new");
    expect(secondPayload.research_doc_id).toBe("doc-2-new");
    expect(secondPayload.qa_doc_id).toBe("doc-3-new");
    expect(secondPayload.glossary_definitions).toEqual({ "SOC 2": "a compliance framework." });
  });

  it("warns that the active provider's key is missing before Generate is ever clicked", async () => {
    const backend = {
      rag: { list: vi.fn().mockResolvedValue([]) },
      context: {
        save: vi.fn().mockResolvedValue({ id: "s1" }),
        prepare: vi.fn().mockResolvedValue({ id: "s1" }),
        researchKeyStatus: vi.fn().mockResolvedValue(false),
      },
      capabilities: vi.fn().mockResolvedValue(null),
    } as unknown as ConvaBackend;

    const initial: ConversationContext = {
      id: "s1",
      title: "Amazon Interview",
      purpose: "",
      job_description: null,
      category: "interview",
      status: "ready",
      created_at_unix_ms: 0,
      updated_at_unix_ms: 0,
      source_doc_ids: [],
      auto_generate_context: true,
      research_enabled: true,
      deep_qa_enabled: false,
      key_terms: [],
      glossary: [],
      glossary_definitions: {},
      knowledge_profile_id: "kp-1",
      personas: [],
      chosen_persona_id: null,
      conversation_id: null,
      dossier_doc_id: "doc-1",
      research_doc_id: null,
      qa_doc_id: "doc-3",
      resources_stale: false,
    };

    render(
      <BackendProvider backend={backend}>
        <ContextSetup initial={initial} onDone={() => undefined} onCancel={() => undefined} />
      </BackendProvider>,
    );

    await screen.findByDisplayValue("Amazon Interview");
    fireEvent.click(screen.getByRole("button", { name: "Next" }));

    // This is the pre-run advisory (researchKeyStatus resolving false) — no
    // Regenerate click has happened, so this is not the post-run report.
    expect(
      await screen.findByText(/Add a Firecrawl key in Settings → Web research \(Context\)/i),
    ).toBeInTheDocument();
    expect(screen.queryByRole("status", { name: /Resource generation results/i })?.children.length ?? 0).toBe(1);
  });

  it("does not render resource generation controls in creation mode", async () => {
    renderSetup();
    const name = await screen.findByPlaceholderText(/Senior Accountant interview/i);
    fireEvent.change(name, { target: { value: "New one" } });
    fireEvent.click(screen.getByRole("button", { name: "Next" }));
    expect(screen.queryByText("Generate Context resources")).toBeNull();
  });

  it("shows a context's own generated document as a badged, view-only row that opens the partner window", async () => {
    const genDoc = {
      id: "g1",
      file_name: "Amazon Interview — Context knowledge",
      enabled: true,
      chunk_count: 3,
      ingested_at_unix_ms: 0,
      source: "generated" as const,
      context_ids: ["s1"],
      size_bytes: 2048,
    };
    const open = vi.fn().mockResolvedValue(undefined);
    const backend = {
      rag: { list: vi.fn().mockResolvedValue([genDoc]) },
      context: { save: vi.fn(), prepare: vi.fn() },
      partner: { open },
      capabilities: vi.fn().mockResolvedValue({ system: { partnerWindow: true } }),
    } as unknown as ConvaBackend;

    render(
      <BackendProvider backend={backend}>
        <ContextSetup
          initial={{ id: "s1", title: "Amazon Interview" } as ConversationContext}
          onDone={() => undefined}
          onCancel={() => undefined}
        />
      </BackendProvider>,
    );

    fireEvent.click(await screen.findByRole("button", { name: "Next" }));
    expect(await screen.findByText("Generate Context resources")).toBeInTheDocument();
    const usedFolder = screen.getByRole("button", { name: /Used by this Context \(1\)/i });
    expect(usedFolder).toHaveAttribute("aria-expanded", "false");
    expect(screen.queryByText(genDoc.file_name)).toBeNull();
    fireEvent.click(usedFolder);
    expect(screen.getByText(genDoc.file_name)).toBeInTheDocument();

    // capabilities() resolves asynchronously (useCapabilities effect) — findBy
    // waits for the View button to appear once it does. The button's
    // accessible name is `View ${file_name}` (aria-label, matching the
    // icon-only View button's pattern in LibraryPane.tsx/ContextDetail.tsx),
    // not bare "View" — match on the prefix.
    fireEvent.click(await screen.findByRole("button", { name: /^View /i }));
    expect(open).toHaveBeenCalledWith(genDoc.file_name, null, null, null, [], "g1");
  });

  it("shows no View button for a generated document when the partner window is unsupported", async () => {
    const genDoc = {
      id: "g1",
      file_name: "Amazon Interview — Context knowledge",
      enabled: true,
      chunk_count: 3,
      ingested_at_unix_ms: 0,
      source: "generated" as const,
      context_ids: ["s1"],
      size_bytes: 2048,
    };
    const backend = {
      rag: { list: vi.fn().mockResolvedValue([genDoc]) },
      context: { save: vi.fn(), prepare: vi.fn() },
      capabilities: vi.fn().mockResolvedValue({ system: { partnerWindow: false } }),
    } as unknown as ConvaBackend;

    render(
      <BackendProvider backend={backend}>
        <ContextSetup
          initial={{ id: "s1", title: "Amazon Interview" } as ConversationContext}
          onDone={() => undefined}
          onCancel={() => undefined}
        />
      </BackendProvider>,
    );

    fireEvent.click(await screen.findByRole("button", { name: "Next" }));
    fireEvent.click(screen.getByRole("button", { name: /Used by this Context \(1\)/i }));
    expect(await screen.findByText(genDoc.file_name)).toBeInTheDocument();
    expect(screen.queryByRole("button", { name: /^View /i })).toBeNull();
  });

  // The bug: these zones read ONLY the in-app DOC_DRAG_MIME payload, so a file
  // dragged from Explorer/Finder hit `onDrop`, found no doc id, and returned —
  // no ingest, no error, nothing. `dragDropEnabled: false` (CLAUDE.md rule 8)
  // means Tauri's onDragDropEvent never fires either, so nothing caught it.
  it("ingests an OS file dropped on a slot and assigns it to that slot", async () => {
    const upload = vi.fn().mockResolvedValue([{ document: ragDoc("n1", "spec.pdf"), warnings: [] }]);
    const list = vi
      .fn()
      .mockResolvedValueOnce([])
      .mockResolvedValue([ragDoc("n1", "spec.pdf")]);
    renderSetup({ rag: { list, upload } as unknown as ConvaBackend["rag"] });
    await gotoStepTwo();

    const zone = screen.getByRole("heading", { name: /résumé \/ cv/i }).closest("div[tabindex]");
    expect(zone).not.toBeNull();
    const file = new File(["contents"], "spec.pdf", { type: "application/pdf" });
    fireEvent.drop(zone as Element, { dataTransfer: transfer({ files: [file] }) });

    await waitFor(() => expect(upload).toHaveBeenCalledTimes(1));
    expect(upload.mock.calls[0][0][0].name).toBe("spec.pdf");
    expect(await screen.findByText("spec.pdf")).toBeInTheDocument();
  });

  it("still assigns an in-app Library drag, which carries a doc id and no files", async () => {
    const upload = vi.fn();
    const list = vi.fn().mockResolvedValue([ragDoc("d1", "resume.pdf")]);
    renderSetup({ rag: { list, upload } as unknown as ConvaBackend["rag"] });
    await gotoStepTwo();

    const zone = screen.getByRole("heading", { name: /résumé \/ cv/i }).closest("div[tabindex]");
    fireEvent.drop(zone as Element, { dataTransfer: transfer({ docId: "d1" }) });

    expect(await screen.findByText("resume.pdf")).toBeInTheDocument();
    // An in-app drag must not be re-ingested as a new upload.
    expect(upload).not.toHaveBeenCalled();
  });

  it("ingests clipboard text pasted onto a slot", async () => {
    const ingestText = vi
      .fn()
      .mockResolvedValue({ document: ragDoc("p1", "Résumé / CV"), warnings: [] });
    const list = vi
      .fn()
      .mockResolvedValueOnce([])
      .mockResolvedValue([ragDoc("p1", "Résumé / CV")]);
    renderSetup({ rag: { list, ingestText } as unknown as ConvaBackend["rag"] });
    await gotoStepTwo();

    const zone = screen.getByRole("heading", { name: /résumé \/ cv/i }).closest("div[tabindex]");
    fireEvent.paste(zone as Element, {
      clipboardData: { files: [], getData: () => "  pasted résumé text  " },
    });

    await waitFor(() => expect(ingestText).toHaveBeenCalledTimes(1));
    // Trimmed, and labelled with the slot it was pasted into.
    expect(ingestText.mock.calls[0][1]).toBe("pasted résumé text");
  });

  it("Paste saves the clipboard as a file and marks it as coming from the clipboard", async () => {
    const ingestText = vi
      .fn()
      .mockResolvedValue({ document: pastedDoc("p1", "Résumé / CV (clipboard)"), warnings: [] });
    const list = vi
      .fn()
      .mockResolvedValueOnce([])
      .mockResolvedValue([pastedDoc("p1", "Résumé / CV (clipboard)")]);
    // No async read() — exercises the readText fallback the button relies on
    // when the clipboard holds plain text.
    Object.assign(navigator, {
      clipboard: { readText: vi.fn().mockResolvedValue("  pasted from the button  ") },
    });
    renderSetup({ rag: { list, ingestText } as unknown as ConvaBackend["rag"] });
    await gotoStepTwo();

    fireEvent.click(screen.getByRole("button", { name: "Paste clipboard into Résumé / CV" }));

    await waitFor(() => expect(ingestText).toHaveBeenCalledTimes(1));
    expect(ingestText.mock.calls[0][1]).toBe("pasted from the button");
    // rag.ingest_text stores DocSource::Pasted, which is what the badge reads —
    // so the saved file is visibly "from clipboard", not just named like it.
    expect(await screen.findByText("From clipboard")).toBeInTheDocument();
  });

  it("saves a clipboard IMAGE as an image file rather than falling back to text", async () => {
    const upload = vi
      .fn()
      .mockResolvedValue([{ document: ragDoc("i1", "clipboard.png"), warnings: [] }]);
    const list = vi.fn().mockResolvedValueOnce([]).mockResolvedValue([ragDoc("i1", "clipboard.png")]);
    const readText = vi.fn().mockResolvedValue("should not be used");
    Object.assign(navigator, {
      clipboard: {
        readText,
        read: vi.fn().mockResolvedValue([
          { types: ["image/png"], getType: vi.fn().mockResolvedValue(new Blob(["x"], { type: "image/png" })) },
        ]),
      },
    });
    renderSetup({ rag: { list, upload } as unknown as ConvaBackend["rag"] });
    await gotoStepTwo();

    fireEvent.click(screen.getByRole("button", { name: "Paste clipboard into Résumé / CV" }));

    await waitFor(() => expect(upload).toHaveBeenCalledTimes(1));
    expect(upload.mock.calls[0][0][0].type).toBe("image/png");
    // A screenshot has no useful text form, so the text path must not run.
    expect(readText).not.toHaveBeenCalled();
  });

  it("offers a delete control on every attached file", async () => {
    const list = vi.fn().mockResolvedValue([ragDoc("d1", "resume.pdf")]);
    renderSetup({ rag: { list } as unknown as ConvaBackend["rag"] });
    await gotoStepTwo();

    const zone = screen
      .getByRole("heading", { name: /résumé \/ cv/i })
      .closest("div[tabindex]") as HTMLElement;
    fireEvent.drop(zone, { dataTransfer: transfer({ docId: "d1" }) });
    // Scope to the slot: the Library column is `hidden xl:block`, but Tailwind
    // classes don't apply in jsdom, so it renders too and lists the same file.
    expect(await within(zone).findByText("resume.pdf")).toBeInTheDocument();

    fireEvent.click(
      screen.getByRole("button", {
        name: "Remove resume.pdf from Résumé / CV — stays in your Library",
      }),
    );
    await waitFor(() => expect(within(zone).queryByText("resume.pdf")).not.toBeInTheDocument());
  });

  it("shows the selected category's slot section labels, and switches them on category change", async () => {
    renderSetup();
    const name = await screen.findByPlaceholderText(/Senior Accountant interview/i);
    fireEvent.change(name, { target: { value: "New one" } });
    fireEvent.click(screen.getByRole("button", { name: "Next" }));
    // Interview is the default type.
    expect(screen.getByRole("heading", { name: /résumé \/ cv/i })).toBeInTheDocument();
    expect(
      screen.getByRole("heading", { name: /take-home \/ test \(multiple\)/i }),
    ).toBeInTheDocument();

    // ViewShell's header Back leaves the sub-view. The persistent workflow
    // footer owns step navigation and labels it Previous.
    fireEvent.click(screen.getByRole("button", { name: "Previous" }));
    fireEvent.click(screen.getByRole("button", { name: "Company meeting" }));
    fireEvent.click(screen.getByRole("button", { name: "Next" }));
    expect(
      screen.getByRole("heading", { name: /financials \/ reports \(multiple\)/i }),
    ).toBeInTheDocument();
    expect(screen.queryByRole("heading", { name: /résumé \/ cv/i })).toBeNull();
  });

  it("shows the category's digest-section preview under the Type picker (Step 1)", async () => {
    renderSetup();
    await screen.findByRole("button", { name: "Interview" });
    expect(
      screen.getByText(
        "Ally will generate: Role profile, Core vocabulary, Likely questions & strong answers, Facts & figures",
      ),
    ).toBeInTheDocument();

    fireEvent.click(screen.getByRole("button", { name: "Other" }));
    expect(
      screen.getByText("Ally will generate: Core vocabulary, Summary, Likely questions"),
    ).toBeInTheDocument();
  });

  it("assigning a Library doc to a section adds it to both selected and slotDocIds in the save payload", async () => {
    const save = vi.fn().mockResolvedValue({ id: "s1" });
    const prepare = vi.fn().mockResolvedValue({ id: "s1" });
    const resumeDoc = {
      id: "d1",
      file_name: "resume.pdf",
      enabled: true,
      chunk_count: 1,
      ingested_at_unix_ms: 0,
      source: "file" as const,
      context_ids: [],
      size_bytes: 100,
    };
    const backend = {
      rag: { list: vi.fn().mockResolvedValue([resumeDoc]) },
      context: { save, prepare },
      capabilities: vi.fn().mockResolvedValue(null),
    } as unknown as ConvaBackend;

    render(
      <BackendProvider backend={backend}>
        <ContextSetup onDone={() => undefined} onCancel={() => undefined} />
      </BackendProvider>,
    );

    const name = await screen.findByPlaceholderText(/Senior Accountant interview/i);
    fireEvent.change(name, { target: { value: "New one" } });
    fireEvent.click(screen.getByRole("button", { name: "Next" }));

    const openPicker = await screen.findByRole("button", { name: "Add from library…" });
    await waitFor(() => expect(openPicker).not.toBeDisabled());
    fireEvent.click(openPicker);
    await screen.findAllByText("resume.pdf");
    fireEvent.click(screen.getByRole("button", { name: "Add resume.pdf to Résumé / CV" }));

    fireEvent.click(screen.getByRole("button", { name: "Next" }));
    fireEvent.click(screen.getByRole("button", { name: "Finish" }));

    await waitFor(() => expect(save).toHaveBeenCalled());
    const payload = save.mock.calls[0][0];
    expect(payload.source_doc_ids).toEqual(["d1"]);
    expect(payload.slot_doc_ids).toEqual({ resume: ["d1"] });
  });

  it("assigning a Library doc to Other documents attaches it without filing it under a slot", async () => {
    const save = vi.fn().mockResolvedValue({ id: "s1" });
    const prepare = vi.fn().mockResolvedValue({ id: "s1" });
    const miscDoc = {
      id: "d1",
      file_name: "misc.txt",
      enabled: true,
      chunk_count: 1,
      ingested_at_unix_ms: 0,
      source: "file" as const,
      context_ids: [],
      size_bytes: 50,
    };
    const backend = {
      rag: { list: vi.fn().mockResolvedValue([miscDoc]) },
      context: { save, prepare },
      capabilities: vi.fn().mockResolvedValue(null),
    } as unknown as ConvaBackend;

    render(
      <BackendProvider backend={backend}>
        <ContextSetup onDone={() => undefined} onCancel={() => undefined} />
      </BackendProvider>,
    );

    const name = await screen.findByPlaceholderText(/Senior Accountant interview/i);
    fireEvent.change(name, { target: { value: "New one" } });
    fireEvent.click(screen.getByRole("button", { name: "Next" }));

    const openPicker = await screen.findByRole("button", { name: "Add from library…" });
    await waitFor(() => expect(openPicker).not.toBeDisabled());
    fireEvent.click(openPicker);
    await screen.findAllByText("misc.txt");
    fireEvent.change(screen.getByRole("combobox", { name: "Resource destination" }), {
      target: { value: "__other__" },
    });
    fireEvent.click(screen.getByRole("button", { name: "Add misc.txt to Other documents" }));

    fireEvent.click(screen.getByRole("button", { name: "Next" }));
    fireEvent.click(screen.getByRole("button", { name: "Finish" }));

    await waitFor(() => expect(save).toHaveBeenCalled());
    const payload = save.mock.calls[0][0];
    expect(payload.source_doc_ids).toEqual(["d1"]);
    expect(payload.slot_doc_ids).toEqual({});
  });

  it("keeps step navigation visible in both the fixed header and workflow footer", async () => {
    renderSetup();
    fireEvent.change(await screen.findByPlaceholderText(/Senior Accountant interview/i), {
      target: { value: "Persistent actions" },
    });

    expect(
      screen.getByRole("button", { name: /Next to context & documents/i }),
    ).toBeInTheDocument();
    expect(screen.getByRole("navigation", { name: "Workflow actions" })).toBeInTheDocument();
    fireEvent.click(screen.getByRole("button", { name: "Next" }));

    expect(screen.getByRole("button", { name: /Next to review/i })).toBeInTheDocument();
    expect(screen.getByRole("button", { name: "Previous" })).toBeInTheDocument();
    expect(screen.getByRole("button", { name: "Next" })).toHaveTextContent("Next: Review");
  });

  it("offers a compact Upload action in every document drop section", async () => {
    renderSetup();
    fireEvent.change(await screen.findByPlaceholderText(/Senior Accountant interview/i), {
      target: { value: "Upload actions" },
    });
    fireEvent.click(screen.getByRole("button", { name: "Next" }));

    expect(screen.getByRole("button", { name: "Upload files to Résumé / CV" })).toBeInTheDocument();
    expect(screen.getByRole("button", { name: "Upload files to Take-home / test" })).toBeInTheDocument();
    expect(screen.getByRole("button", { name: "Upload files to Other documents" })).toBeInTheDocument();
  });
});
