import { cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { afterEach, describe, expect, it, vi } from "vitest";

import { ContextSetup } from "@/components/context/ContextSetup";
import { BackendProvider } from "@/lib/backend";
import type { ConvaBackend } from "@/lib/backend/ConvaBackend";
import type { ConversationContext } from "@/lib/ipc";

afterEach(cleanup);

// Minimal fake — the wizard only calls rag.list() on mount; the rest is local
// React state until Finish (which these tests don't reach). capabilities()
// is stubbed because ContextSetup now calls useCapabilities() unconditionally
// (Generated by Ally's View button gating) — resolving null is fine for
// tests that don't care about partnerWindow.
function fakeBackend(): ConvaBackend {
  return {
    rag: { list: vi.fn().mockResolvedValue([]) },
    capabilities: vi.fn().mockResolvedValue(null),
  } as unknown as ConvaBackend;
}

function renderSetup() {
  render(
    <BackendProvider backend={fakeBackend()}>
      <ContextSetup onDone={() => undefined} onCancel={() => undefined} />
    </BackendProvider>,
  );
}

describe("ContextSetup wizard", () => {
  it("offers the four conversation types", async () => {
    renderSetup();
    // findBy flushes the mount effect (rag.list) so no act() warnings.
    expect(await screen.findByRole("button", { name: "Interview" })).toBeInTheDocument();
    for (const type of ["Company meeting", "Sales call", "Other"]) {
      expect(screen.getByRole("button", { name: type })).toBeInTheDocument();
    }
  });

  it("shows the job-description field only for Interview", async () => {
    renderSetup();
    // Interview is the default type → JD field present.
    expect(await screen.findByPlaceholderText(/job description/i)).toBeInTheDocument();
    // Switching to an internal type hides it.
    fireEvent.click(screen.getByRole("button", { name: "Company meeting" }));
    expect(screen.queryByPlaceholderText(/job description/i)).toBeNull();
  });

  it("defaults web research on for the Interview type", async () => {
    renderSetup();
    // Name is required to advance to step 2.
    const name = await screen.findByPlaceholderText(/Senior Accountant interview/i);
    fireEvent.change(name, { target: { value: "My interview" } });
    fireEvent.click(screen.getByRole("button", { name: "Next" }));
    // The research toggle (now joined on step 2 by the interview-only deep
    // Q&A checkbox) is on by default for Interview.
    expect(
      screen.getByRole("checkbox", { name: /research the web for context/i }),
    ).toBeChecked();
  });

  it("preserves generated-document ids and derived fields across an edit-save", async () => {
    const save = vi.fn().mockResolvedValue({ id: "s1" });
    const prepare = vi.fn().mockResolvedValue({ id: "s1" });
    const backend = {
      rag: { list: vi.fn().mockResolvedValue([]) },
      context: { save, prepare },
      capabilities: vi.fn().mockResolvedValue(null),
    } as unknown as ConvaBackend;

    const initial: ConversationContext = {
      id: "s1",
      title: "Amazon Interview",
      purpose: "",
      job_description: null,
      category: "interview",
      status: "ready",
      created_at_unix_ms: 0,
      updated_at_unix_ms: 0,
      source_doc_ids: [],
      auto_generate_context: true,
      research_enabled: true,
      deep_qa_enabled: true,
      key_terms: [],
      glossary: [],
      glossary_definitions: { "API Gateway": "managed API front door." },
      knowledge_profile_id: "kp-1",
      personas: [],
      chosen_persona_id: null,
      conversation_id: null,
      dossier_doc_id: "doc-1",
      research_doc_id: "doc-2",
      qa_doc_id: "doc-3",
      resources_stale: true,
    };

    render(
      <BackendProvider backend={backend}>
        <ContextSetup initial={initial} onDone={() => undefined} onCancel={() => undefined} />
      </BackendProvider>,
    );

    await screen.findByDisplayValue("Amazon Interview");
    fireEvent.click(screen.getByRole("button", { name: "Next" }));
    fireEvent.click(screen.getByRole("button", { name: "Next" }));
    fireEvent.click(screen.getByRole("button", { name: "Finish" }));

    await waitFor(() => expect(save).toHaveBeenCalled());
    const payload = save.mock.calls[0][0];
    expect(payload.research_doc_id).toBe("doc-2");
    expect(payload.qa_doc_id).toBe("doc-3");
    expect(payload.glossary_definitions).toEqual({ "API Gateway": "managed API front door." });
    expect(payload.resources_stale).toBe(true);
  });

  it("saves pending edits (e.g. a just-checked deep-QA box) before regenerating, and keeps later saves in sync with the fresh doc ids", async () => {
    const save = vi.fn().mockResolvedValue({ id: "s1" });
    const generateDossier = vi.fn().mockResolvedValue({
      id: "s1",
      dossier_doc_id: "doc-1-new",
      research_doc_id: "doc-2-new",
      qa_doc_id: "doc-3-new",
      glossary: ["SOC 2"],
      glossary_definitions: { "SOC 2": "a compliance framework." },
      resources_stale: false,
    });
    const prepare = vi.fn().mockResolvedValue({ id: "s1" });
    const backend = {
      rag: { list: vi.fn().mockResolvedValue([]) },
      context: { save, generateDossier, prepare },
      capabilities: vi.fn().mockResolvedValue(null),
    } as unknown as ConvaBackend;

    const initial: ConversationContext = {
      id: "s1",
      title: "Amazon Interview",
      purpose: "",
      job_description: null,
      category: "interview",
      status: "ready",
      created_at_unix_ms: 0,
      updated_at_unix_ms: 0,
      source_doc_ids: [],
      auto_generate_context: true,
      research_enabled: true,
      deep_qa_enabled: false,
      key_terms: [],
      glossary: [],
      glossary_definitions: {},
      knowledge_profile_id: "kp-1",
      personas: [],
      chosen_persona_id: null,
      conversation_id: null,
      dossier_doc_id: "doc-1",
      research_doc_id: "doc-2",
      qa_doc_id: "doc-3",
      resources_stale: false,
    };

    render(
      <BackendProvider backend={backend}>
        <ContextSetup initial={initial} onDone={() => undefined} onCancel={() => undefined} />
      </BackendProvider>,
    );

    await screen.findByDisplayValue("Amazon Interview");
    fireEvent.click(screen.getByRole("button", { name: "Next" }));

    // Check the deep-QA box — local wizard state only, not yet persisted.
    fireEvent.click(
      screen.getByRole("checkbox", { name: /research common interview questions/i }),
    );
    fireEvent.click(screen.getByRole("button", { name: "Regenerate resources" }));

    // The save that regenerate fires must carry the just-checked box — the
    // concrete bug this closes: generateDossier reads the saved session
    // from disk, so without this save it silently ran against the old
    // (unchecked) value and produced no Q&A doc.
    await waitFor(() => expect(save).toHaveBeenCalled());
    expect(save.mock.calls[0]![0].deep_qa_enabled).toBe(true);
    expect(generateDossier).toHaveBeenCalledWith("s1");

    // A later save (e.g. Finish, without another edit) must use the FRESH
    // doc ids generateDossier just returned, not the stale `initial` ones —
    // otherwise it would silently revert the just-regenerated docs.
    await waitFor(() => expect(generateDossier).toHaveReturned());
    fireEvent.click(screen.getByRole("button", { name: "Next" }));
    fireEvent.click(screen.getByRole("button", { name: "Finish" }));
    await waitFor(() => expect(save).toHaveBeenCalledTimes(2));
    const secondPayload = save.mock.calls[1]![0];
    expect(secondPayload.dossier_doc_id).toBe("doc-1-new");
    expect(secondPayload.research_doc_id).toBe("doc-2-new");
    expect(secondPayload.qa_doc_id).toBe("doc-3-new");
    expect(secondPayload.glossary_definitions).toEqual({ "SOC 2": "a compliance framework." });
  });

  it("does not render the Generated by Ally section in creation mode", async () => {
    renderSetup();
    const name = await screen.findByPlaceholderText(/Senior Accountant interview/i);
    fireEvent.change(name, { target: { value: "New one" } });
    fireEvent.click(screen.getByRole("button", { name: "Next" }));
    expect(screen.queryByText("Generated by Ally")).toBeNull();
  });

  it("shows a context's own generated document as a badged, view-only row that opens the partner window", async () => {
    const genDoc = {
      id: "g1",
      file_name: "Amazon Interview — Context knowledge",
      enabled: true,
      chunk_count: 3,
      ingested_at_unix_ms: 0,
      source: "generated" as const,
      context_ids: ["s1"],
    };
    const open = vi.fn().mockResolvedValue(undefined);
    const backend = {
      rag: { list: vi.fn().mockResolvedValue([genDoc]) },
      context: { save: vi.fn(), prepare: vi.fn() },
      partner: { open },
      capabilities: vi.fn().mockResolvedValue({ system: { partnerWindow: true } }),
    } as unknown as ConvaBackend;

    render(
      <BackendProvider backend={backend}>
        <ContextSetup
          initial={{ id: "s1", title: "Amazon Interview" } as ConversationContext}
          onDone={() => undefined}
          onCancel={() => undefined}
        />
      </BackendProvider>,
    );

    fireEvent.click(await screen.findByRole("button", { name: "Next" }));
    expect(await screen.findByText("Generated by Ally")).toBeInTheDocument();
    expect(screen.getByText(genDoc.file_name)).toBeInTheDocument();
    // No checkbox for a generated row — only an attachable row would have one.
    expect(screen.queryByRole("checkbox", { name: `Attach ${genDoc.file_name}` })).toBeNull();

    // capabilities() resolves asynchronously (useCapabilities effect) — findBy
    // waits for the View button to appear once it does. The button's
    // accessible name is `View ${file_name}` (aria-label, matching the
    // icon-only View button's pattern in LibraryPane.tsx/ContextDetail.tsx),
    // not bare "View" — match on the prefix.
    fireEvent.click(await screen.findByRole("button", { name: /^View /i }));
    expect(open).toHaveBeenCalledWith(genDoc.file_name, null, null, null, [], "g1");
  });

  it("shows no View button for a generated document when the partner window is unsupported", async () => {
    const genDoc = {
      id: "g1",
      file_name: "Amazon Interview — Context knowledge",
      enabled: true,
      chunk_count: 3,
      ingested_at_unix_ms: 0,
      source: "generated" as const,
      context_ids: ["s1"],
    };
    const backend = {
      rag: { list: vi.fn().mockResolvedValue([genDoc]) },
      context: { save: vi.fn(), prepare: vi.fn() },
      capabilities: vi.fn().mockResolvedValue({ system: { partnerWindow: false } }),
    } as unknown as ConvaBackend;

    render(
      <BackendProvider backend={backend}>
        <ContextSetup
          initial={{ id: "s1", title: "Amazon Interview" } as ConversationContext}
          onDone={() => undefined}
          onCancel={() => undefined}
        />
      </BackendProvider>,
    );

    fireEvent.click(await screen.findByRole("button", { name: "Next" }));
    expect(await screen.findByText(genDoc.file_name)).toBeInTheDocument();
    expect(screen.queryByRole("button", { name: /^View /i })).toBeNull();
  });
});
