//! SimCon shell storage — the platform half of the Simulated Conversation
//! feature. The pure data model lives in `conva_core::simcon`; this module is
//! the fs/`AppHandle` side, mirroring `conversations.rs`.
//!
//! Storage: one pretty-printed JSON file per SimCon under
//! `<app-data>/simcon/`. (KnowledgeProfile + persona persistence arrive with
//! the ingestion/persona pipeline — Phase C/D.)

use std::fs;
use std::path::{Path, PathBuf};

use tauri::{AppHandle, Manager};

use conva_core::simcon::{SimConSession, SimConSummary};
use conva_core::CoreError;

use crate::session::now_unix_ms;

fn simcon_dir(app: &AppHandle) -> Result<PathBuf, CoreError> {
    let dir = app
        .path()
        .app_data_dir()
        .map_err(|e| CoreError::Audio(format!("no app data dir: {e}")))?
        .join("simcon");
    fs::create_dir_all(&dir).map_err(|e| CoreError::Audio(e.to_string()))?;
    Ok(dir)
}

fn validate_id(id: &str) -> Result<(), CoreError> {
    // ids are generated by us, but never trust them as path components.
    if id.is_empty() || id.contains(['/', '\\', '.']) {
        return Err(CoreError::Audio("invalid simcon id".into()));
    }
    Ok(())
}

/// Create or update a SimCon. An **empty `id`** mints a new record (assigns an
/// id + `created_at`); an existing id updates in place, preserving `created_at`.
/// `updated_at` is always stamped now.
pub fn save(app: &AppHandle, mut session: SimConSession) -> Result<SimConSession, CoreError> {
    let now = now_unix_ms();
    if session.id.is_empty() {
        session.id = format!("sim-{now}");
        session.created_at_unix_ms = now;
    } else {
        validate_id(&session.id)?;
        if let Ok(existing) = load(app, &session.id) {
            session.created_at_unix_ms = existing.created_at_unix_ms;
        }
    }
    session.updated_at_unix_ms = now;

    let path = simcon_dir(app)?.join(format!("{}.json", session.id));
    let json =
        serde_json::to_string_pretty(&session).map_err(|e| CoreError::Audio(e.to_string()))?;
    fs::write(path, json).map_err(|e| CoreError::Audio(e.to_string()))?;
    Ok(session)
}

pub fn load(app: &AppHandle, id: &str) -> Result<SimConSession, CoreError> {
    validate_id(id)?;
    let path = simcon_dir(app)?.join(format!("{id}.json"));
    let content = fs::read_to_string(path).map_err(|e| CoreError::Audio(e.to_string()))?;
    serde_json::from_str(&content).map_err(|e| CoreError::Audio(e.to_string()))
}

pub fn delete(app: &AppHandle, id: &str) -> Result<(), CoreError> {
    validate_id(id)?;
    let path = simcon_dir(app)?.join(format!("{id}.json"));
    fs::remove_file(path).map_err(|e| CoreError::Audio(e.to_string()))
}

/// Catalog for the list view — newest first, without loading full personas.
pub fn list(app: &AppHandle) -> Result<Vec<SimConSummary>, CoreError> {
    let dir = simcon_dir(app)?;
    let mut out = Vec::new();
    for entry in fs::read_dir(&dir)
        .map_err(|e| CoreError::Audio(e.to_string()))?
        .flatten()
    {
        let path = entry.path();
        if path.extension().and_then(|e| e.to_str()) != Some("json") {
            continue;
        }
        let Ok(content) = fs::read_to_string(&path) else {
            continue;
        };
        let Ok(s) = serde_json::from_str::<SimConSession>(&content) else {
            continue;
        };
        out.push(SimConSummary {
            id: s.id,
            title: s.title,
            category: s.category,
            status: s.status,
            created_at_unix_ms: s.created_at_unix_ms,
            updated_at_unix_ms: s.updated_at_unix_ms,
        });
    }
    out.sort_by(|a, b| b.updated_at_unix_ms.cmp(&a.updated_at_unix_ms));
    Ok(out)
}

/// A filesystem-safe slug of a Sim Con title, for its document folder name.
fn slug(title: &str) -> String {
    let mut s = String::new();
    let mut prev_dash = false;
    for c in title.trim().chars() {
        if c.is_alphanumeric() {
            s.push(c.to_ascii_lowercase());
            prev_dash = false;
        } else if !prev_dash {
            s.push('-');
            prev_dash = true;
        }
    }
    let s = s.trim_matches('-').chars().take(60).collect::<String>();
    if s.is_empty() {
        "untitled".to_string()
    } else {
        s
    }
}

/// The Sim Con's own document folder: `<app-data>/simcon/<slug(title)>/`, so a
/// rehearsal's source documents live together, named after it.
pub fn doc_folder(app: &AppHandle, title: &str) -> Result<PathBuf, CoreError> {
    let folder = simcon_dir(app)?.join(slug(title));
    fs::create_dir_all(&folder).map_err(|e| CoreError::Audio(e.to_string()))?;
    Ok(folder)
}

/// Copy documents added at setup into this Sim Con's folder and return their new
/// paths (the caller then ingests them into the RAG library for retrieval).
pub fn store_docs(
    app: &AppHandle,
    title: &str,
    paths: Vec<String>,
) -> Result<Vec<String>, CoreError> {
    let folder = doc_folder(app, title)?;
    let mut out = Vec::new();
    for p in paths {
        let src = Path::new(&p);
        let name = src
            .file_name()
            .and_then(|n| n.to_str())
            .unwrap_or("document");
        let dest = folder.join(name);
        fs::copy(src, &dest).map_err(|e| CoreError::Audio(e.to_string()))?;
        out.push(dest.to_string_lossy().to_string());
    }
    Ok(out)
}
