//! SimCon shell storage — the platform half of the Simulated Conversation
//! feature. The pure data model lives in `conva_core::simcon`; this module is
//! the fs/`AppHandle` side, mirroring `conversations.rs`.
//!
//! Storage: one pretty-printed JSON file per SimCon under
//! `<app-data>/simcon/`. (KnowledgeProfile + persona persistence arrive with
//! the ingestion/persona pipeline — Phase C/D.)

use std::fs;
use std::path::{Path, PathBuf};

use tauri::{AppHandle, Manager};

use conva_core::simcon::{
    extract_glossary, KnowledgeProfile, ResearchSource, SimConCategory, SimConSession,
    SimConStatus, SimConSummary, DEFAULT_CONTEXT_ID,
};
use conva_core::CoreError;

use crate::rag::RagStore;
use crate::session::now_unix_ms;

/// Baseline "General conversation" briefing, compiled into the binary so it's
/// always present regardless of packaging/cwd (unlike the repo-relative
/// `library/`/`conva.config.json` seed convention, which only resolves in a
/// git checkout). v1, hand-authored; the community-voting + LLM-inference
/// evolution (design doc) replaces this with something that keeps itself
/// current.
const DEFAULT_DIGEST_TEXT: &str = include_str!("../resources/default-context.md");

fn simcon_dir(app: &AppHandle) -> Result<PathBuf, CoreError> {
    let dir = app
        .path()
        .app_data_dir()
        .map_err(|e| CoreError::Audio(format!("no app data dir: {e}")))?
        .join("simcon");
    fs::create_dir_all(&dir).map_err(|e| CoreError::Audio(e.to_string()))?;
    Ok(dir)
}

fn validate_id(id: &str) -> Result<(), CoreError> {
    // ids are generated by us, but never trust them as path components.
    if id.is_empty() || id.contains(['/', '\\', '.']) {
        return Err(CoreError::Audio("invalid simcon id".into()));
    }
    Ok(())
}

/// Seed the always-present default context ("General conversation") on first
/// launch — the target of session-grounding's "required selection" invariant
/// (a fresh install has something to select from turn one). Idempotent:
/// no-ops once `DEFAULT_CONTEXT_ID` already exists, so it's safe to call on
/// every startup and never overwrites a later smart-evolution update. Purely
/// local (no network) — safe to run synchronously during app setup.
pub fn ensure_default_context(app: &AppHandle, rag: &RagStore) -> Result<(), CoreError> {
    if load(app, DEFAULT_CONTEXT_ID).is_ok() {
        return Ok(()); // already seeded (or since updated by a future version)
    }

    let report = rag.ingest_generated(
        "General conversation — baseline briefing",
        DEFAULT_DIGEST_TEXT,
        DEFAULT_CONTEXT_ID,
    )?;
    let doc_id = report.document.id.clone();
    let now = now_unix_ms();

    let profile_id = format!("kp-{DEFAULT_CONTEXT_ID}");
    save_profile(
        app,
        &KnowledgeProfile {
            id: profile_id.clone(),
            title: "General conversation".to_string(),
            created_at_unix_ms: now,
            updated_at_unix_ms: now,
            doc_ids: vec![doc_id.clone()],
            research: Vec::new(),
            ready: true,
        },
    )?;

    save(
        app,
        SimConSession {
            id: DEFAULT_CONTEXT_ID.to_string(),
            title: "General conversation".to_string(),
            purpose: "Baseline grounding for any call — used when nothing more \
specific is active."
                .to_string(),
            job_description: None,
            category: SimConCategory::Other,
            status: SimConStatus::Ready,
            created_at_unix_ms: now,
            updated_at_unix_ms: now,
            source_doc_ids: vec![doc_id.clone()],
            auto_generate_context: false,
            research_enabled: false,
            key_terms: Vec::new(),
            glossary: extract_glossary(DEFAULT_DIGEST_TEXT),
            glossary_definitions: std::collections::BTreeMap::new(),
            knowledge_profile_id: Some(profile_id),
            personas: Vec::new(),
            chosen_persona_id: None,
            conversation_id: None,
            dossier_doc_id: Some(doc_id),
            research_doc_id: None,
            resources_stale: false,
        },
    )?;
    Ok(())
}

/// Create or update a SimCon. An **empty `id`** mints a new record (assigns an
/// id + `created_at`); an existing id updates in place, preserving `created_at`.
/// `updated_at` is always stamped now.
pub fn save(app: &AppHandle, mut session: SimConSession) -> Result<SimConSession, CoreError> {
    let now = now_unix_ms();
    if session.id.is_empty() {
        session.id = format!("sim-{now}");
        session.created_at_unix_ms = now;
    } else {
        validate_id(&session.id)?;
        if let Ok(old) = load(app, &session.id) {
            session.created_at_unix_ms = old.created_at_unix_ms;
            // Grounding edits invalidate derived state (spec 2026-08-26, part 1):
            // the glossary derives from the OLD inputs, so clear it (the next
            // activation re-mines JD-first; the next Generate rebuilds it from the
            // fresh digest), and mark generated resources stale so the UI can say
            // "regenerate". Internal saves (dossier, personas, activation backfill)
            // change no grounding fields and pass through untouched.
            if conva_core::simcon::grounding_changed(&old, &session) {
                session.glossary.clear();
                if old.dossier_doc_id.is_some() || old.knowledge_profile_id.is_some() {
                    session.resources_stale = true;
                }
            }
        }
    }
    session.updated_at_unix_ms = now;

    let path = simcon_dir(app)?.join(format!("{}.json", session.id));
    let json =
        serde_json::to_string_pretty(&session).map_err(|e| CoreError::Audio(e.to_string()))?;
    fs::write(path, json).map_err(|e| CoreError::Audio(e.to_string()))?;
    Ok(session)
}

pub fn load(app: &AppHandle, id: &str) -> Result<SimConSession, CoreError> {
    validate_id(id)?;
    let path = simcon_dir(app)?.join(format!("{id}.json"));
    let content = fs::read_to_string(path).map_err(|e| CoreError::Audio(e.to_string()))?;
    serde_json::from_str(&content).map_err(|e| CoreError::Audio(e.to_string()))
}

pub fn delete(app: &AppHandle, id: &str) -> Result<(), CoreError> {
    validate_id(id)?;
    let path = simcon_dir(app)?.join(format!("{id}.json"));
    fs::remove_file(path).map_err(|e| CoreError::Audio(e.to_string()))
}

/// Catalog for the list view — newest first, without loading full personas.
pub fn list(app: &AppHandle) -> Result<Vec<SimConSummary>, CoreError> {
    let dir = simcon_dir(app)?;
    let mut out = Vec::new();
    for entry in fs::read_dir(&dir)
        .map_err(|e| CoreError::Audio(e.to_string()))?
        .flatten()
    {
        let path = entry.path();
        if path.extension().and_then(|e| e.to_str()) != Some("json") {
            continue;
        }
        let Ok(content) = fs::read_to_string(&path) else {
            continue;
        };
        let Ok(s) = serde_json::from_str::<SimConSession>(&content) else {
            continue;
        };
        out.push(SimConSummary {
            id: s.id,
            title: s.title,
            category: s.category,
            status: s.status,
            created_at_unix_ms: s.created_at_unix_ms,
            updated_at_unix_ms: s.updated_at_unix_ms,
            source_doc_count: s.source_doc_ids.len() as u32,
            has_key_terms: !s.key_terms.is_empty(),
            research_enabled: s.research_enabled,
            has_job_description: s
                .job_description
                .as_deref()
                .is_some_and(|jd| !jd.trim().is_empty()),
            has_generated_resources: s.dossier_doc_id.is_some(),
            resources_stale: s.resources_stale,
        });
    }
    out.sort_by_key(|b| std::cmp::Reverse(b.updated_at_unix_ms));
    Ok(out)
}

/// A filesystem-safe slug of a Sim Con title, for its document folder name.
fn slug(title: &str) -> String {
    let mut s = String::new();
    let mut prev_dash = false;
    for c in title.trim().chars() {
        if c.is_alphanumeric() {
            s.push(c.to_ascii_lowercase());
            prev_dash = false;
        } else if !prev_dash {
            s.push('-');
            prev_dash = true;
        }
    }
    let s = s.trim_matches('-').chars().take(60).collect::<String>();
    if s.is_empty() {
        "untitled".to_string()
    } else {
        s
    }
}

/// The Sim Con's own document folder: `<app-data>/simcon/<slug(title)>/`, so a
/// rehearsal's source documents live together, named after it.
pub fn doc_folder(app: &AppHandle, title: &str) -> Result<PathBuf, CoreError> {
    let folder = simcon_dir(app)?.join(slug(title));
    fs::create_dir_all(&folder).map_err(|e| CoreError::Audio(e.to_string()))?;
    Ok(folder)
}

/// Copy documents added at setup into this Sim Con's folder and return their new
/// paths (the caller then ingests them into the RAG library for retrieval).
pub fn store_docs(
    app: &AppHandle,
    title: &str,
    paths: Vec<String>,
) -> Result<Vec<String>, CoreError> {
    let folder = doc_folder(app, title)?;
    let mut out = Vec::new();
    for p in paths {
        let src = Path::new(&p);
        let name = src
            .file_name()
            .and_then(|n| n.to_str())
            .unwrap_or("document");
        let dest = folder.join(name);
        fs::copy(src, &dest).map_err(|e| CoreError::Audio(e.to_string()))?;
        out.push(dest.to_string_lossy().to_string());
    }
    Ok(out)
}

// ── KnowledgeProfile — the reusable indexed knowledge base ──────────────────

fn profiles_dir(app: &AppHandle) -> Result<PathBuf, CoreError> {
    let dir = simcon_dir(app)?.join("profiles");
    fs::create_dir_all(&dir).map_err(|e| CoreError::Audio(e.to_string()))?;
    Ok(dir)
}

pub fn save_profile(app: &AppHandle, profile: &KnowledgeProfile) -> Result<(), CoreError> {
    validate_id(&profile.id)?;
    let path = profiles_dir(app)?.join(format!("{}.json", profile.id));
    let json =
        serde_json::to_string_pretty(profile).map_err(|e| CoreError::Audio(e.to_string()))?;
    fs::write(path, json).map_err(|e| CoreError::Audio(e.to_string()))
}

pub fn load_profile(app: &AppHandle, id: &str) -> Result<KnowledgeProfile, CoreError> {
    validate_id(id)?;
    let path = profiles_dir(app)?.join(format!("{id}.json"));
    let content = fs::read_to_string(path).map_err(|e| CoreError::Audio(e.to_string()))?;
    serde_json::from_str(&content).map_err(|e| CoreError::Audio(e.to_string()))
}

/// Build (or rebuild) the reusable `KnowledgeProfile` for a Sim Con from its
/// attached documents (already ingested in the RAG library) plus web research,
/// then mark the session ready. Reuses the session's existing profile id if it
/// has one, so re-preparing after an edit updates in place.
///
/// The attached-doc side works today; the web-research list is filled by
/// [`research`] only when a search API key is configured (Phase C.2) — otherwise
/// it stays empty and the profile is docs-only.
pub fn prepare(app: &AppHandle, id: &str) -> Result<SimConSession, CoreError> {
    let mut session = load(app, id)?;
    let now = now_unix_ms();
    let profile_id = session
        .knowledge_profile_id
        .clone()
        .unwrap_or_else(|| format!("kp-{now}"));
    let created = load_profile(app, &profile_id)
        .map(|p| p.created_at_unix_ms)
        .unwrap_or(now);

    // Web research runs when enabled for this context (defaults from the type
    // template — decision 2). The legacy auto-generate flag still opts in.
    let research = if session.research_enabled || session.auto_generate_context {
        match research(&session, &[]) {
            Ok((sources, searches)) => {
                // Tavily bills per search — record what we actually issued.
                crate::metering::record_tavily_search(app, searches);
                sources
            }
            Err(_) => Vec::new(),
        }
    } else {
        Vec::new()
    };

    let profile = KnowledgeProfile {
        id: profile_id.clone(),
        title: session.title.clone(),
        created_at_unix_ms: created,
        updated_at_unix_ms: now,
        doc_ids: session.source_doc_ids.clone(),
        research,
        ready: true,
    };
    save_profile(app, &profile)?;

    session.knowledge_profile_id = Some(profile_id);
    session.status = SimConStatus::Ready;
    save(app, session)
}

// ── Web research (Step 2) — Tavily, keyed from the OS vault ─────────────────

const TAVILY_KEYRING_SERVICE: &str = "conva";
const TAVILY_KEYRING_USER: &str = "api-key-tavily";
/// Hard budget so research can never run slow or expensive (SDLC/owner ask).
const RESEARCH_MAX_QUERIES: usize = 6;
const RESEARCH_MAX_SOURCES: usize = 12;

pub fn store_tavily_key(key: &str) -> Result<(), CoreError> {
    let entry = keyring::Entry::new(TAVILY_KEYRING_SERVICE, TAVILY_KEYRING_USER)
        .map_err(|e| CoreError::Audio(e.to_string()))?;
    if key.trim().is_empty() {
        match entry.delete_credential() {
            Ok(()) | Err(keyring::Error::NoEntry) => Ok(()),
            Err(e) => Err(CoreError::Audio(e.to_string())),
        }
    } else {
        entry
            .set_password(key.trim())
            .map_err(|e| CoreError::Audio(e.to_string()))
    }
}

pub fn load_tavily_key() -> Option<String> {
    keyring::Entry::new(TAVILY_KEYRING_SERVICE, TAVILY_KEYRING_USER)
        .ok()?
        .get_password()
        .ok()
}

/// Bounded autonomous web research (Step 2) via Tavily. Returns the sources to
/// fold into the KnowledgeProfile plus the number of Tavily searches issued
/// (each is one billed search — the caller records it for usage metering). No
/// key configured → returns empty (the profile is docs-only). Failures per query
/// are skipped, never fatal. Runs on a command thread, never the UI path.
pub(crate) fn research(
    session: &SimConSession,
    vocabulary: &[String],
) -> Result<(Vec<ResearchSource>, u64), CoreError> {
    let Some(key) = load_tavily_key() else {
        return Ok((Vec::new(), 0));
    };
    let mut out: Vec<ResearchSource> = Vec::new();
    let mut searches: u64 = 0;
    for query in conva_core::simcon::research_queries(session, vocabulary, RESEARCH_MAX_QUERIES) {
        if out.len() >= RESEARCH_MAX_SOURCES {
            break;
        }
        searches += 1;
        let body = serde_json::json!({
            "api_key": key,
            "query": query,
            "max_results": 3,
            "search_depth": "basic",
        });
        let resp = ureq::post("https://api.tavily.com/search")
            .timeout(std::time::Duration::from_secs(15))
            .send_json(body);
        let val: serde_json::Value = match resp {
            Ok(r) => match r.into_json() {
                Ok(v) => v,
                Err(_) => continue,
            },
            Err(_) => continue,
        };
        let Some(results) = val.get("results").and_then(|r| r.as_array()) else {
            continue;
        };
        for r in results {
            if out.len() >= RESEARCH_MAX_SOURCES {
                break;
            }
            let url = r.get("url").and_then(|v| v.as_str()).unwrap_or("");
            if url.is_empty() {
                continue;
            }
            out.push(ResearchSource {
                title: r
                    .get("title")
                    .and_then(|v| v.as_str())
                    .unwrap_or("")
                    .to_string(),
                url: url.to_string(),
                snippet: r
                    .get("content")
                    .and_then(|v| v.as_str())
                    .unwrap_or("")
                    .chars()
                    // Tavily's content excerpt — the findings synthesis
                    // needs more than a headline.
                    .take(1_200)
                    .collect(),
                fetched_at_unix_ms: now_unix_ms(),
            });
        }
    }
    Ok((out, searches))
}

#[cfg(test)]
mod tests {
    use super::*;

    // ensure_default_context() itself needs a real AppHandle (no
    // tauri::test mocking is wired into this crate yet) — these cover the
    // pure part: the shipped digest's shape, so an edit that breaks its
    // `## Glossary` heading or leaves it empty fails CI, not a live user.

    #[test]
    fn default_digest_is_non_empty_and_well_formed() {
        assert!(!DEFAULT_DIGEST_TEXT.trim().is_empty());
        for heading in ["## Overview", "## Glossary", "## Good practices"] {
            assert!(
                DEFAULT_DIGEST_TEXT.contains(heading),
                "missing {heading} in default-context.md"
            );
        }
    }

    #[test]
    fn default_digest_glossary_extracts_cleanly() {
        let terms = extract_glossary(DEFAULT_DIGEST_TEXT);
        assert!(!terms.is_empty(), "no glossary terms extracted");
        for expected in ["Stakeholder", "ROI", "SLA", "KPI"] {
            assert!(
                terms.iter().any(|t| t == expected),
                "expected {expected} in {terms:?}"
            );
        }
    }
}
